cmake_minimum_required(VERSION 3.20)
project(TradingSystem)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
add_subdirectory(libs/reference-data )
add_subdirectory(libs/order-book)
add_subdirectory(libs/position_manager)
add_subdirectory(libs/fix_session)
add_subdirectory(src)
